nodeID:ID	nodeKind	loc	locRange	type	valueKind	value	castKind	declName	semcontext	lexcontext	declqual	baredeclref
1	TranslationUnit	/home/bhargava/work/gitlab/llvm-joern-frontend/tests/basic.c	 <<invalid sloc>>									
2	Function	/home/bhargava/work/gitlab/llvm-joern-frontend/tests/basic.c:1:5	 <col:1, line:3:1>					main				
3	CompoundStmt		 <line:1:12, line:3:1>									
4	ReturnStmt		 <line:2:2, col:9>									
5	IntegerLiteral		 <col:9>	<int>								
